name: Build
on: [push, pull_request]
jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    -  name: Docker NGINX build
    -  run: |
         docker build ./nginx -t kowhai/ckan-docker-nginx:testing-only
        