name: Build CKAN Docker 

on: [push, pull_request]

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    -  name: Docker NGINX build
       run: |
         docker build ./nginx -t kowhai/ckan-docker-nginx:testing-only
    -  name: Docker postgres build
       run: |
         docker build ./postgresql -t kowhai/ckan-docker-postgresql:testing-only
    -  name: Docker solr build
       run: |
         docker build ./solr -t kowhai/ckan-docker-solr:testing-only
        